@baseURL=http://localhost:3000/api

@resourceName=blogMoives

###
#GetAllCommentCinema
GET {{baseURL}}/{{resourceName}}

#CinemasComent
# @name getAllComentMoiveByMaRap
GET {{baseURL}}/{{resourceName}}?maPhim=1526

###

# @name addNewComentMoive
POST  {{baseURL}}/{{resourceName}}
Content-Type: application/json

    {
        "maPhim":1526,
        "userName":"sang",
        "text":"hay ko ta"
    }
####

# @name deletedComentMoiveById
DELETE    {{baseURL}}/{{resourceName}}/2
Content-Type: application/json

    {
        "maPhim":1526,
        "userName":"sang",
        "text":"hay ko ta"
    }

