@baseURL=http://localhost:3000/api

@resourceName=blogs

@maPhim=maPhim
@maRap=maRap
###
#GetAllCommentCinema
GET {{baseURL}}/{{resourceName}}?{{maRap}}=bhd

#####

#CinemasComent
# @name getAllComentMoiveByMaRap
GET {{baseURL}}/{{resourceName}}?{{maPhim}}=1324

