@baseURL=http://localhost:3000/api

@resourceName=blogCinemas

#CinemasComent

#GetAllCinemaComment
GET {{baseURL}}/{{resourceName}}

# @name getAllComentCinemaByMaRap
GET {{baseURL}}/{{resourceName}}?maRap=bhd-cong-hoa

###

# @name addNewComentCinema
POST  {{baseURL}}/{{resourceName}}
Content-Type: application/json

    {
        "maRap":"bhd-ton-duc-thang",
        "userName":"minhPhuc",
        "text":"de xem thu"
    }
####

# @name deletedComentCinemaById
DELETE    {{baseURL}}/{{resourceName}}/4
Content-Type: application/json

    {
        "maRap":"bhd-3-2",
        "userName":"minhPhuc",
        "text":"de xem thu"
    }

